- name: Provision Lab
  hosts: localhost
  become: true
  vars:
    availability_zones: 3

  tasks:
    - name: Swarm
      ansible.builtin.import_role:
        name: swarm_node

      vars:
        swarm_node_count: "{{ availability_zones }}"
